# Description:
#   Generates a devops against humanity pair form http://devopsagainsthumanity.com/
#
# Dependencies:
#   None
#
# Configuration:
#   HUBOT_HIPCHAT_TOKEN
#
# Commands:
#   hubot devops card me - Returns a random card against humanity with emoji
#
# Author:
#   KevinBehrens

Util = require "util"

black_cards = [
  "__________ is weaponized privilege."
  "__________ logs or it didn't happen."
  "__________, for some values of __________."
  "Ask Me Anything about __________."
  "Called on account of __________."
  "Disrupting the established players in __________ via __________."
  "Doge __________."
  "Employees must __________ before returning to work."
  "Enterprise __________ in the cloud."
  "Enterprise-ready __________."
  "Epic yak-shave caused by __________."
  "Facebook has acquired __________ for $10b and __________."
  "Free as in __________."
  "Glitter-bombed with __________."
  "Hi, I'm Troy McClure. You may remember me from such commit messages as __________ and __________."
  "How is __________ even formed?"
  "I can haz __________."
  "Tinder for __________"
  "I saw the best minds of my generation __________."
  "If __________ is the answer, you are asking the wrong question."
  "If you're using __________, you're gonna have a bad time."
  "Nobody ever got fired for buying __________."
  "Running Windows in production leads to __________."
  "The Internet is for cat memes and __________."
  "\"Our release schedule doesn't have time for __________.\""
  "The Internet of Things will be controlled by __________."
  "The only thing necessary for evil to triumph is __________."
  "Uber is on surge pricing because of __________."
  "WARN: __________ has been deprecated."
  "Will merge pull requests for __________."
  "Zero-day __________."
  "Time to schedule the postmortem for __________. ."
  "__________ - the idiots guide to __________ and __________."
  "Put some ___________ on it"
  "Wrap it with the __________ duct tape"
  "But Google is using __________ so we should too!"
  "__________ is the new __________."
  "Etsy says we should __________ everything."
  "xkcd.com just made a hilarious comic making fun of __________."
  "This isn't going to be all unicorns and __________."
  "Apple just patented __________."
  "When I was a kid we didn't have __________."
  "__________ is a nice idea, lets found a start-up."
  "DevOps: Now with 100% more __________!"
  "Main benefits of automation: __________ and __________."
  "Chef convergence failed due to __________."
  "...and then there was the time I found __________ on the root partition."
  "We run production on __________ and __________."
  "Management said it's OK to deploy __________ at 5pm on Friday "
  "Did you know that we have __________ on pager rotation?"
  "\"There was no good solution for __________, so we built our own.\""
  "Amazon built a datacenter on the moon to lessen the risk of __________ causing problems."
  "In order to improve security, we're upgrading to __________."
  "The two pillars of our Continuous Deployment pipeline are __________ and __________."
  "I got paged at 3am because of __________."
  "The most stable part of our infrastructure? __________"
  "When I told Jez Humble about our __________, he actually cried."
  "When I write a book about my experiences, it'll be called \"__________, the good parts\""
  "Restoring from backups failed due to __________."
  "My two most indispensable tools are __________ and __________."
  "The production datacenter burned down because of __________."
  "It turns out that the button labeled \"Don't Push\" actually does __________."
  "You should think of your servers like __________ and not like __________."
  "I find Java to be way too __________."
  "It's like trying to herd __________."
  "I ended up having to buy a replacement __________ on eBay."
  "__________ is more memory than anyone will ever need on a computer."
  "__________ Driven Development."
  "The RIAA is suing me for downloading __________."
  "Security? We've got that! We use __________."
  "sudo pip install __________"
  "When I hooked the 3D printer up to the Internet, it accidentally created __________."
  "My next blog post will be about how we used __________ to create __________."
  "So, I was using Wireshark to check network traffic... Did you know we have __________ in production?"
  "My eyes started bleeding when I opened the editor and saw __________."
  "I think maybe I'll leave __________ off my resumé."
  "We don't need __________ - we have __________ !"
  "Management just told me I need to get certified in __________."
  "Our app is like __________, but for __________."
  "Marketing says we're leaders in the __________ space, but I think it's more accurate to say we specialize in __________."
  "Our greatest achievement in the last year is __________."
  "I write my code in vim because of __________"
  "If we make this deadline, Management has promised us __________."
  "Sweet! I just found a Puppet module for __________!"
  "Last week, I created a Chef recipe for __________; this week, it's an entire cookbook for __________, Automation FTW!"
  "We really need to open-source our __________."
  "A sales rep just tried to pitch me on __________; I told them we already have __________."
  "Who would have known that __________ could destroy an entire datacenter?"
  "sudo apt-get install __________"
  "Our production backups are stored using __________."
  "We replaced our __________ with __________"
  "After __________ came up, the retrospective really went downhill."
  "You know what our app needs? More __________, less __________."
  "It figures - an article about our __________ was posted just as we're pivoting to __________."
  "In the next planning session, we'll cover __________ and __________."
  "Our competitive advantage is our __________."
  "Every time someone brings up __________, I throw up a little in my mouth."
  "Continuous __________."
  "All that we had to do to halve our response times was implement __________"
  "Our entire app is geared towards providing __________."
  "__________-ility"
  "We just achieved __________s per second!"
  "You now have a scroll titled '_____________' (f)"
  "__________ is that even HA?"
  "My Linkedin Endorsements include __________."
  "Users are __________."
  "Robots are going to make __________ obsolete."
  "Accidental __________."
  "An error occurred: E__________"
  "According to the logs, __________ was initially caused by __________."
  "We can just fix that with a little ___________."
  "You can have __________, __________, or __________.  Pick two."
  "A monad is just a __________ in the category of __________, what's the problem?"
  "Functional programming - if you can't __________ it, __________ it."
  "On a scale from 1 to 10, this is __________!"
  "We don't need configuration management, we have __________!"
  "__________, now with __________ support."
  "RedHat has announced that RHEL 8 will ship with __________."
  "\"Hey, __________ is down. Can you fix it?\""
  "I grabbed __________ on my way out the door after our paychecks bounced and management stopped answering their phones."
  "Did you try __________ yet?"
  "I was 6 beers in when I got the pager alert that __________was down."
  "Notice: Building __________ for __________"
  "I laughed when they said I'd be on call 24/7 but wouldn't receive a stipend for __________."
  "If it weren't for __________ we'd all be __________."
  "__________, __________ and just a few lines of Perl."
  "NoSQL is superior to SQL because __________"
  "Script kiddies got into __________ because __________."
  "__________ is better than Hadoop because __________"
  "Disturbing ____ leaves ____ fucked"
  "Rub a little __________ on it"
  "WAIT, YOU DELETED __________??!"
  "@__________borat"
  "It's not web scale, it's __________"
  "The tech support hotline told me to __________"
  "Asynchronous REST API calls are the solution to __________"
  "Say concurrent threads again and I will __________ you."
  "\"Guys, seriously, if we just use __________ it will solve all our problems with __________!\""
  "Facebook changed their profiles today because __________."
  "github.com/__________/__________"
  "Hello. My name is __________ and I am addicted to __________ ."
  "__________ dependency hell."
  "That talk outline said it would be about __________, but it ended up being more like __________."
  "I will replace you with a very small ___________."
  "Jordan Sissel hates ___________ so much that he created a new opensource project called __________ to work around it."
  "__________ isn't a job title"
  "For the next project we are going to use __________ to solve __________ ."
  "My editor of choice is __________."
  "__________ it; ship it."
  "__________-Stack Developer"
  "__________SQL"
  "That's not a hacker, that's my __________! "
  "It has been __ days since the last __________"
  "I've __________ things you people wouldn't __________"
  "The __________ on the server were deleted because __________ ."
  "This week, Aphyr runs __________ through jepsen."
  "The intern just ran __________ on the load balancer."
  "I need you to do a __________ with __________ before __________ ."
  "Lambdas are just a lame implementation of __________."
  "C-x; C-__________"
  "This users wants __________ because __________ ."
  "__________ should be deprecated in favour of __________ ."
  "__________ mismatch between __________ and __________"
  "I put __________ on the scripts to make it run faster."
  "Developers do not get access to production machines, because of __________."
  "Developers need access to production machines because __________."
  "We run __________ in a cron job every 15 minutes."
  "The client says it needs more __________ ."
  "We're a __________ as a Service company."
  "I could hire a __________ to do your job!"
  "My next Velocity talk is called \"__________ops\""
  "The RFO for the global outage was __________ compunded by __________"
  "I was hired to maintain this 20 year old script that runs our critical __________ infrastructure."
  "Amazon Elastic __________"
  "I know we use __________, but I wrote this critical program in __________."
  "I'll just have Ops spin up a couple of __________ environments."
  "I'm writing my next IRC bot with __________."
  "SIG____"
  "I cannot wait until someone makes a __________ cluster out of these."
  "C will finally be displaced by __________"
  "____________________.io"
  "We don't need to worry about __________, We're using MongoDB."
  "Why is ___________ better than Hadoop?"
  "FC067: __________"
  "Oh, the __________ is just a hack to get the __________ to run."
  "How do I even __________ ?"
  "__________ all the things."
  "ERROR: __________ NOT FOUND"
  "We don't need backups, we've got __________."
  "Fixing your father's computer with __________."
  "it's always a __________ DNS problem"
  "__________ with this one weird trick."
  "__________ isn't new, we used to do it in the '70s on mainframes."
  "Puppet is better than Chef because __________ and __________"
  "How is __________ better than __________ ?"
  "Learn ____ the hard way"
  "vagrant up __________"
  "bollocks up __________"
  "You can fix  __________ with __________ ."
  "We took the plunge and rewrote ____________ in Go"
  "Implementing _______________________ should take only 2 lines of code."
  "I accidentally the entire _____________________ is this dangerous?"
  "Good enough for _____________ work"
  "Yeah, but can it run ______________?Y"
  "Security through __________."
  "__________? You can safely ignore that. Usually."
  "__________ isn't cool. You know what's cool? __________"
  "I made a new editor, better than vim and emacs. It's called __________"
  "640k should be enough for __________."
  "__________ worked in dev."
  "You can't fix __________"
  "How hard could it be to port Linux to __________."
  "I just finished working on my rocket powered __________."
  "Richard Stallman will kill you with his teeth for __________."
  "DB tuning with __________."
  "Can anyone help me get __________ running on Cisco IOS?"
  "Real __________ don't use __________"
  "__________ on XEN"
  "Please bring back __________. You broke my workflow."
  "I cut-and-pasted this StackOverflow code for my __________."
  "I'm just finishing up my manifesto on __________."
  "r/__________."
  "We can discuss __________ at the stand-up meeting."
  "A Beowulf cluster of __________."
  "We're demoing __________ for __________ at SXSW."
  "I aliased __________ to git __________."
  "10 PRINT \"__________\"; GOTO 10"
  "alt.binaries.__________"
  "It is completely dark. You are likely to be eaten by a __________."
  "Conway's Game of __________."
  "Next year I'll start learning __________"
  "s/__________/__________/g"
  "__________ is the newest gTLD"
  "Works on my __________."
  "One does not simply __________"
  "Sorry, you'll need to open a ticket before we can __________."
  "ln -s __________ __________"
  "__________"
  "__________ is dead."
  "__________. WTF does that mean?"
  "Make it __________."
  "__________coin."
  "__________ computing"
  "grep __________ | mail __________"
  "__________ just got pwned."
  "It's like __________, but with __________ and list comprehensions."
  "Software Defined __________."
  "I don't have any UNIX Beards in stock, but we do have  __________"
  "Amazon does __________, why can't we?"
  "__________ nagios"
  "I can't believe you're still using __________."
  "/dev/___________: Device is busy"
  "__________, You don't exist, go away!"
  "I tried __________, The doctors say I'll never walk again."
  "git --__________"
  "The __________ Public License."
  "__________ begins with __________."
  "Couldn't we use __________?"
  "__________ would be so much better if we rewrote it in Clojure."
  "So I just found __________ and __________ running in a screen session."
  "Why is root running __________ under tmux?"
  "Instead of installing __________, what if we just used __________"
  "I need a webinar like I need __________."
  "Fuck it, time to break out the emergency __________."
  "On the plus side, we finally got rid of __________."
  "__________ thought leader."
  "Fuck it: __________ looks good to me."
  "It looks like you're trying to __________. Can I help?"
  "bash: command not found: __________"
  "ETOOMUCH__________"
  "How did __________ ever work?"
  "Whoops, I thought that method was supposed to __________ the __________"
  "I thought you said __________ was secure?"
  "git: You are in detached __________ state."
  "Why don't we just fork __________ ?"
  "Network dropped connection because of __________."
  "We turned off __________ and everything magically got better."
  "I found a Samba share full of __________"
  "__________. What could go wrong?"
  "Install ___________"
  "I installed __________ by accident."
  "Read-eval-__________-loop."
  "We should try it with an actual __________."
  "Is __________ something we need to optimize for?"
  "Hack __________ into redis."
  "__________ Considered Harmful"
  "Never __________ before a demonstration"
  "The __________ is used when the CPU is on fire"
  "modperl can be used to implement __________"
  "__________ runs Ruby as root"
  "Larry Wall trained as missionary then __________"
  "Listening to the fans in the server farm leads to __________"
  "__________ and __________ are rumoured to be working on a python module for a helicam"
  "A lot of disk space is needed for __________"
  "automagical __________"
  "Whoever made the unscheduled change to production on Friday will be forced to use __________."
  "Install __________"
  "Never question the ____"
  "I can't wait until we no longer use __________"
  "I bet if we switch to __________ it will just work"
  "__________ has just discovered __________.  We're doomed."
  "A neckbeard made of __________."
  "False alarm, it was just __________ running __________."
  "__________ running on a rack of __________."
  "No, __________ being hopelessly broken is NOT an emergency."
  "Our new startup is the __________ for __________."
  "__________ make me a sandwich"
  "__________ over IP"
  "__________ is a hardware problem."
  "I AM working, I'm waiting for the __________ run to finish."
  "The first rule of __________ is: You do not talk about __________."
  "Google Analytics says 100% of my website visitors are __________"
  "__________ will never get job in Microsoft"
  "4chan.org is powered by __________."
  "We can __________ just like Netflix"
  "__________ is how I resolve all merge conflicts."
  "Why does someone keep re-implementing system utilities in __________?"
  "Remember when you told me to tell you when you were acting __________ and __________? ---you're doing it now. "
  "Our only hope at recovering the data is __________"
  "__________: the gift that keeps on giving."
  "__________ has been killed with fire.  My work is done here."
  "Problem exists between Keyboard and __________"
  "100% government funded __________!"
  "The __________ certification program."
  "__________? I'd hit that."
  "__________ makes robots moves"
  "I just finished writing an API for __________."
  "__________ is a batch command to shut the fuck up"
  "__________.  Failed to cache catalog."
  "Everytime you allocate you have to __________ when you're done"
  "Sorry, I'm all out of __________-fu."
  "90% of everything is __________."
  "Given enough __________, all bugs are __________."
  "__________ never use on git"
  "The first 90% of development is __________. The second 90% is __________."
  "When you logged in there, did you see a __________ that said __________"
  "Purely numeric hostname and not a __________ -----rejecting!"
  "I'm pretty sure __________ isn't thread safe"
  "We don't have to worry about CAP Theorem because of __________."
  "I don't always test my code, but when I do I do it in __________."
  "Those who don't understand __________ are condemned to reinvent it, poorly"
  "The NSA is really interested in our latest project: __________."
  "Just change the __________, it'll be fine. "
  "Yeah, you need to modprobe __________ to get it to recognize the __________"
  "Oh, we're devops! We have ___________ in the office, but only the DBA can touch it."
  "We're spending 20% of this sprint doing __________."
  "__________ found a new OpenSSL vulernability people are calling __________."
  "Management has changed all our job titles to __________."
  "while true; do ____; done"
  "The consultant we hired is certain that __________ will drastically increase the performance of __________"
  "Could you just push this update for __________?  It should be a no-op."
  "If we're all going to get fired, let's get fired for __________."
  "We can't pay you, but we can offer __________ in compensation."
  "A soiled napkin with the contents of __________ scribbled on it"
  "Who thought that ____________ was a good idea?"
  "It's not the recommended configuration to use __________ with __________ but it's in production right now."
  "We wrote our own build tool based on __________"
  "I've received a Microsoft MVP Award for __________"
  "We rewrote __________ in __________"
  "The ticket to install __________?  I deletegated it."
  "Some people, when confronted with a problem, think \"I know, I'll use __________.\" Now they have two problems."
  "Artisanally crafted __________."
  "The backups are fine, but the restore process is __________"
  "I can't believe QA made a ticket for __________"
  "The __________ that ops provides developers."
  "Oracle is proud to announce that the next edition of Java features ___________"
  "Move __________ and break things."
  "__________: ci or not ci?"
  "I opened the server cabinet and it was full of __________."
  "Crossing __________ could lead to total protonic reversal."
  "The next big thing is __________"
  "I once made a robot around the concept of __________"
  "I __________ your stupid issue!"
  "Nine circles of __________ hell."
  "I once wrote an NPM module called __________.js"
  "I asked the contractor for __________ and they delivered __________."
  "Welcome to Programming 101, our first topic will be ___________"
  "The Genius Bar recommends you try ___________"
  "Post-modern coding is defined by ______________"
  "__________ | sudo sh"
  "ASP has finally developed and replaced __________"
  "__________ has been put under the WTFPLicense"
  "Here's __________, as I promised."
  "I'd like __________, __________, and a Fluttershy."
  "It compiles __________ to JavaScript."
  "Only the Enterprise Edition(tm) has __________."
  "__________ is a proof of concept and an actual __________ __________"
  "The trouble with kids these days is __________"
  "___________ is the new Stalinism."
  "__________ for the win!"
  "__________ is the new __________"
  "Don't read the __________ or the __________ pages"
  "With __________, you write once, run nowhere."
  "__________ discontinued support for the Linux version."
  "A manager told me I couldn't remove our dependency on __________, but I got around it with __________."
  "__________ implements every single standard for __________.  Poorly."
  "Just think of the Internet as __________."
  "Would you like __________ with that?"
  "__________? We've got that."
  "It took over 40 hours to document __________. "
  "//TODO: __________."
  "npm install __________."
  "Circular imports import __________. "
  "A firewall rule for ____."
  "__________ is why the jDBA thought it might be time to go to #mysql on freenode"
  "__________ is the only reason the jDBA survived typing rm -rf /"
  "__________ exists?"
  "It's like __________ on __________."
  "I came here to drink milk and __________, and I've just finished my milk. "
  "End-to-end __________."
  "__________ will help you remember to sanitze your database inputs."
  "Fascists cannot stand __________."
  "0.______________________________"
  "RTFM so you can _____________________."
  "__________ took EBS down again today."
  "I ssh'd into a server running __________ and promptly noped the fuck out of there."
  "__________, the final solution."
  "We're running __________ in production?!"
  "__________ has root access."
  "We don't have enough package managers said __________"
  "__________ is more reliable than ___________"
  "Of course culture is important to us, that's why we have __________."
  "I'd trust all my stuff to __________."
  "__________ ass-as-sin-vice."
  "My __________ for a __________."
  "Nice __________ I'll take it."
  "@horse__________"
  "such __________. wow."
  "That's funny, did ____ used to be here?"
  "I can't believe you improved ___________ by deleting ____________________"
  "The only thing more dangerous than __________ is a programmer with __________"
  "1.  _____________ 2. ______________  3. Profit."
  "\"Monads are easy! Just think of them as ______________\""
  "__________: powered by the cloud."
  "I upload my worm to __________"
  "I fork my children with __________"
  "Multiple backend penetration  is achieved with __________"
  "You can force kill your children by __________"
  "__________ corrupts your children's memory"
  "#!/bin/__________"
  "make __________ && sudo make install"
  "I bet the person who wrote this uses __________."
  "I'm not __________, my code is compiling."
  "Don't worry, we have unit tests for __________."
  "As a __________, I want __________."
  "The only non-conformance in this year's audit was __________."
  "Blaming intern for the __________"
  "__________ is my favourite thing about __________"
  "I wish that we had more __________ in our office"
  "I've once been so drunk that __________ actually made sense"
  "To understand __________ you must first understand __________."
  "__________ @ 127.0.0.1 -p __________"
  "__________? You mean __________!"
  "__________ is coming out of stealth mode"
  "__________ ate all my memory"
  "__________ is always a good practice."
  "Don't mind me, I'm just practicing __________ ."
  "We accidently the whole __________."
  "It's easy! Just run __________"
  "I assure you __________ is secure!"
  "Our backup policy is __________"
  "____ the XML in that JSON file"
  "pacman -Syu accidentally __________ everything"
  "I saw a High Scalability blog post about __________"
  "\"We didn't think anyone was using __________!\""
  "Do you wanna build a __________?"
  "IBM just created JSONxx to encapsulate JSON in XML in __________"
  "I never truly understood eXtreme programming until I encountered __________"
  "The Agile Manifesto taught me to pick __________ over __________"
  "__________ should be a singleton!"
  "Flash is dying because __________"
  "Neo, the matrix has one fatal flaw, you must find __________"
  "Javascript is the best language ever, thanks to __________"
  "Last night while drunk, the W3C declared __________ as a new web standard."
  "North Korea finally launched warheads because of __________"
  "Last night I accidentally ran sudo chmod -R 777 /. I just blame ___________."
  "During the lunch break I like to think about __________."
  "Nobody will value your work if you don't use __________ "
  "__________, because scientists don't know how to code"
  "__________, because Knuth."
  "The entire system failed because of __________"
  "The meeting between Europe and the USA was cancelled because of __________"
  "We missed the launch window due to confusion from __________"
  "__________ wasted thousands of dollars"
  "No one can authenticate because of ___________"
  "__________ caused the servers to melt down"
  "__________ invalidated all the assumptions in our monitoring system"
  "__________ because __________."
  "CAMS is outdated because of __________."
  "__________: Easy one-step installation"
  "__________, because even the hobos of Market Street need a cluster scheduler."
  "We need to update the _____________"
  "It's cool, they use __________ at Etsy."
  "Code as __________."
  "__________ is how the cloud works."
  "How does it look in Opera?"
  "The __________ shell"
  "__________ in haskell"
  "Say __________ one more time; I dare you!"
  "The cloud runs on __________, with a bit of __________."
  "__________, because who needs monitoring. "
  "This problem can be completely solved with __________ implemented in __________."
  "__________ vs __________... fight!"
  "I regret to inform you your weekend has been revoked due to __________."
  "All alerts go to ____, which is handled by __________."
  "__________, it's the new pink."
  "I've got 99 problems but __________ ain't one."
  "140 characters is just enough to explain __________."
  "__________ all the way down."
  "___________ continuously spawns zombie processes"
  "Elliptic-Curve Diffie-Helman breaks against ____________"
  "Why isn't my script working?"
  "ITIL best practices suggest __________ is the next step"
  "We would have gotten the funding, if only our slide deck included __________"
  "Have you tried __________ and __________ ?"
  "Why can't I login to the VPN?"
  "I left __________ in the server room."
  "I stuck my hand in a sysadmin's beard and pulled out __________"
  "Before exiting, the program kills __________"
  "Cookbooks containing __________ have been known to cause __________"
  "Once we added __________ to the firewall rules, __________ worked perfectly"
  "My pre-commit hook replaces tab characters with __________"
  "I was up all night debugging __________"
  "Error: insufficient __________"
  "The Product Team handed me a spec, they want __________ in the next release of __________"
  "The malware came from an infected ad on __________ .com"
  "Killing child processes releases resources back to __________"
  "That regular expression is designed to match __________ but not __________"
  "The vendor solution didn't have log aggregation, but it did have __________"
  "Our custom log rotation scripts have the added feature of __________"
  "This year, Cross-Site Request Forgery (CSRF) was knocked out of the OWASP Top 10, and replaced by __________"
  "Nagios sucks, let's replace it with __________"
  "My pull request was rejected because it contained __________"
  "My stacktrace revealed __________"
  "Chef encountered an error attempting to create __________"
  "Since the 1950s, engineers have been striving toward a more effective means of generating __________"
  "Our code was efficient, except for the module containing __________, which was slower than __________"
  "I need to re-munge the CSV, replacing the commas with __________"
  "We strive for continuous deployment, continuous delivery, and continuous __________"
  "Data-driven decisions are to be replaced with __________"
  "The ruby gem is useless, it's a lesser implementation of __________"
  "Windows ME had a service pack that solved the problem of __________"
  "Lennart Poettering's latest project is __________."
  "\"__________ is the quickest way to identify what is burning in the server room.  \""
  "Oh, we store all our docs in __________."
  "I accidentally __________ the whole database."
  "It's not a bug it's a ___________."
  "What killed the mood at E3?"
  "To replace camelCase, the new C++ standards mandate variables be named using __________."
  "I'm sorry __________ isn't numberwang."
  "I'm sorry __________ isn't wangernum."
  "\"__________ became self aware and kidnapped the sysadmins.\""
  "That's the first time I've ever seen ProGuard used to obfuscate __________."
  "Every day at work I implement __________ and my mother still tells her friends I \"do computers\"."
  "That's the first time I've ever seen comments written in __________."
  "It's not a problem, I'll just __________ it later"
]

white_cards = [
  "The Cult of Mac"
  "Developers"
  "fuckedcompany.com"
  "Git"
  "Golang"
  "Growth hacking"
  "Hacker News"
  "Larry Ellison"
  "Leaky abstractions"
  "Meritocracy"
  "MongoDB"
  "Node.js"
  "NPM"
  "Pareto Inefficient Nash Equilibriums"
  "Posting on Etsy's codeascraft blog"
  "Python"
  "Python datetime module"
  "Rebasing the entire fucking repo"
  "Recruiter Fail"
  "Ruby"
  "Running out of IPv4 addresses"
  "Sysadmins"
  "The Stanford of Canada"
  "Thought leadership"
  "Twitter"
  "Unicode errors"
  "Unknown source in your stack trace"
  "Waiting for console.aws.amazon.com"
  "Women in tech"
  "Yet another package manager"
  "Our Release Engineer"
  "OpenSSL"
  "Heartbleed"
  "The NSA"
  "O'Reilly"
  "Edward Snowden"
  "Google"
  "Magic Spray"
  "Web scale"
  "Functional programming"
  "Stack trace generator"
  "PHP? Oh dear god why?!"
  "SVN"
  "Perl 6"
  "COTS Shareware"
  "2400 baud modem"
  "A squirrel with a taste for fiber"
  "Zombie processes"
  "CAP Theorem"
  "Snowflake server"
  "A Cisco router with a flaky chip"
  "NullPointerException: null"
  "Apache 1.2 running as root"
  "More buzzwords than you can shake a scrum at"
  "it better not have, why wouldn't you text"
  "VisualBasic DLLs"
  "A JAR full of spaghetti"
  "An epic caffeine bender"
  "A WSDL from 2003"
  "The Sales & Marketing department"
  "Business logic in PowerPoint slides"
  "/var/log symlinked to /dev/null"
  "Hypervisors running hypervisors running hypervisors"
  "An angry badger with an electromagnet on its back"
  "A shared root password"
  "Private keys in /var/www"
  "Parsing HTML with regex"
  "A 3.5\" floppy disk"
  "An untested restore process"
  "A cron job that reboots the server every 5 minutes"
  "Apache Zookeeper on a 286"
  "Sadness as a Service"
  "Cloud-based business strategy"
  "Cloud 2.0"
  "The next Y2K"
  "An army of chaos monkeys, all carrying flamethrowers"
  "A CORBA service written in Ada which communicates using JSONx"
  "A home-rolled systemd replacement"
  "A custom kernel with Frontpage Extensions installed"
  "A mobile web 2.0 RIA"
  "Agony-Driven Development"
  "Being acquired by Oracle"
  "Catastrophic Failure as a Service"
  "10,000 Nagios alerts per second"
  "A global write lock"
  "75-tier architecture"
  "Hand-crafted artisan x86 assembly code:q"
  "The world's only fully-functional ROFLcopter"
  "A proof that P=NP written in BASIC"
  "An Exchange email loop"
  "A Volker-Craig terminal"
  "A self-aware PHP script"
  "A 500-megabyte UDP packet"
  "The last remaining Multics server on Earth"
  "A Null-modem cable"
  "A turducken made entirely of bash scripts"
  "Write-only code"
  "PagerDuty configured with a random number generator"
  "Netscape Navigator 3.2 support"
  "dd"
  "A Piñata full of error messages"
  "Mutation of immutable data"
  "Maven downloading the entire internet"
  "Continuous Disintegration"
  "IE6"
  "Scrum Master"
  "Magic Smoke"
  "done done"
  "Tech Debt Day"
  "Log Shipping"
  "uucp"
  "4chan Party Van"
  "Adderall"
  "Tcl"
  "NoOps"
  "An angry whale shitting containers"
  ":(){ :|:& };:"
  "Too Big Data"
  "Accidentally the entire data center"
  "freebasing caffeine"
  "Fat fingered"
  "Half open TCP connections"
  "Steve Ballmer wielding a battleaxe"
  "A 50k line Bash script that's achieved self awareness"
  "Gigadevops"
  "Enterprise Grade Bash scripts"
  "Agile"
  "A pink sombrero and a fifth of tequila"
  "A simple 15 level Hiera hierarachy"
  "lolscale."
  "CouchDB"
  "GeoCouchDB"
  "High Availability"
  "Map-Reduce"
  "Web Scale?"
  "Erlang"
  "a non-ironic BSOD"
  "ntpdate"
  "Systemd"
  "12 factor application"
  "Fail early, fail often"
  "Regex"
  "A violation of the most basic engineering principles."
  "The BOFH"
  "A water buffalo"
  "a routing loop"
  "a queue with no consumers"
  "Bitcoin mining"
  "A firewall full of holes"
  "An uncontrollable deluge of emails"
  "I heard about it on hacker news"
  "Ycombinator"
  "a jailbroken iPad"
  "\"Fuck it, we'll do it live!\""
  "Vagrant"
  "Nokogiri Gem"
  "Docker"
  "a \"MRW\" animated gif"
  "$HOME/.gem"
  "a posting on Craigslist \"internet engineers\" jobs forum"
  "ssh in a for loop"
  "a cold cup of coffee"
  "Destroying your tools with your tools"
  "UTF-9"
  "a dozen vendor t-shirts"
  "unlimited data plan"
  "UTF-7"
  "out-of-band access"
  "sudo rm -rf /"
  "kill -9"
  "a series of tiny shellscripts"
  "Dogecoin"
  "Kernel panic"
  "Hugops!"
  "Lolcats"
  "Culture"
  "Percussive maintenance"
  "IE 7 Support"
  "Hangops"
  "Unix philosophy"
  "Trying to install MongoDB on AIX 3"
  "A server rack full of crushed dreams"
  "Monads"
  "Silos"
  "Elastic Load Balancers"
  "RFC1178"
  "Full-stack developer"
  "Andrew Clay Shaffer"
  "Jordan Sissel"
  "A new printer."
  "A potato"
  "Office Space"
  "Git Blame"
  "Developers! Developers! Developers! Developers!"
  "Your account"
  "Single stepping through the kernel"
  "De-linting source code"
  "Significant whitespace"
  "A series of tubes"
  "secret sauce"
  "# What is this used for?"
  "Regular Expressions"
  "# FIXME: For now, just don't validate"
  "ASAP"
  "Nagios"
  "The Goddamn CDN"
  "Authentication and authorization"
  "A cluster of applications on a cluster of servers"
  "Beating the server into submission with your bare hands."
  "Read-only Fridays"
  "r/sysadmin"
  "Distributed Computing"
  "Sprint Planning"
  "Merge Conflicts"
  "# we *LIE* about what happened and return a \"success\""
  "Unplugging a server and waiting to see who complains"
  "THE MAGMA PEOPLE ARE WAITING FOR OUR MISTAKES."
  "a tiny ounce of knowledge"
  "Too big to fail"
  "NoQA Movement"
  "A few instances"
  "operations hipster"
  "Cowboy developer"
  "cubism farm"
  "HipChat"
  "An IRC bot written entirely in sed"
  "(╯°□°）╯︵ ┻━┻"
  "works for me"
  "a torrent of Torrenters torrenting"
  "COBOL"
  "in b4 FIRST"
  "Donald Knuth"
  "Rebooting All The Things"
  "Running Openstack in Production"
  "the Berkshelf way"
  "DNS"
  "SIGHUP"
  "Animated GIF"
  "PC LOAD LETTER"
  "Automate"
  "Delightful"
  "Cache"
  "Proxy"
  "an online book seller"
  "Dust Bunnies"
  "Pete Cheslock"
  "Networking"
  "A sad log with a mustache"
  "Blue Screen Of Death"
  "ISO 8601"
  "Daniel J. Bernstein"
  "Linus Torvalds"
  "Broadcom chipset"
  "Moe"
  "That XKCD comic about sysadmins"
  "iso 8859"
  "RFC 1149"
  "A pimply faced youth with nothing to lose"
  "Theo de Raadt yelling at newbs"
  "Hate driven development"
  "Lotus123"
  "IPSec"
  "Hackathons"
  "GNU/Linux"
  "ZeroVM"
  "Stringing cloudtobutt.pl into postfix."
  "ZeroMQ over SSH"
  "SQLite"
  "LevelDB"
  "Leap second bug"
  "The fucking JVM"
  "continuous deployment"
  "Tor"
  "bash"
  "numactl"
  "zsh"
  "Standing around outside on the streets of SOMA with an overheating laptop drunk while fixing your god damn Saturday night deployment."
  "Vegan friendly init scripts."
  "Committing from the bar."
  "Servers that follow daylight savings time."
  "Rolling Grubhub into the build failed script."
  "command line options"
  "Temporary hotfixes"
  "jsLinux"
  "SIGKILL"
  "Your private browsing history"
  "top"
  "Arguing over the internet."
  "year 2038"
  "dd"
  "pdisk"
  "rsync"
  "CFLAGS"
  "cowsay"
  "profanity in the git log"
  "Gentoo"
  "The CEO"
  "Ping Pong"
  "Dennis Ritchie"
  "PAM Happy Hour"
  "Complex systems usually operate in failure mode."
  "FAT32"
  "winsock"
  "fork() on Windows"
  "runlists"
  "sudo"
  "echo shell_exec(\"sudo ./smbkill \".escapeshellcmd($_GET['kill']).\" 2>&1\");"
  "kill -9 -1"
  "curl 4chan | sudo sh"
  "HTML9 Responsive Boilerstrap JS"
  "Neckbeards"
  "A Certified SCRUM Master"
  "Bus error"
  "git reset --hard origin/master"
  "Forcing push to master"
  "Paxos"
  "LogFiles\W3SVC1"
  "A German installation of Windows NT4"
  "curl | sh -c"
  "OpenLDAP"
  "Spot Instances"
  "Those ksh scripts"
  "/cgi-bin/php5"
  "A $60 QNAP and some positive thinking"
  "raspberryPI"
  "Windows ME"
  "@echo off"
  "Active Directory"
  "conflict minerals"
  "continuous incineration"
  "The gentle sound of weeping drifting from the server room"
  "eventual consistency"
  "Microsoft® Azure"
  "Pinging the broadcast address"
  "That moment when you realize CTRL-Z cannot save you"
  "127.0.0.1"
  "Ethernet"
  "IPv6"
  "Re-writing deployment scripts at 2 AM"
  "Piping /var/log/messages to Twitter"
  "A pseudorandom number generator"
  "An outage window"
  "Sentinel System Driver"
  "fpm"
  "catastrophic cancellation"
  "termcap"
  "f00d"
  "one giant SPOF"
  "Richard Stallman's Neckbeard"
  "phpMyAdmin"
  "Righteous Anger"
  "/etc/hosts"
  "CEOs with root access"
  "Automagic Metaprogramming"
  "Re-implementing TCP over UDP"
  "Segfault"
  "#define BEGIN  {"
  "Microsoft Access over a WAN"
  "git submodules"
  "Haskell"
  "Functional Reactive"
  "Paxos"
  "memegen"
  "Flynn"
  "eventual persistence"
  "Jenkins"
  "Bingo Balls"
  "Mechanically Recovered Turkey"
  "ChatOps"
  "Scala"
  "WONTFIX"
  "Trello board"
  "mechanically recovered data"
  "Friday afternoon deployment"
  "YoloDB"
  "Piping random scripts from the internet into bash"
  "(╯°□°）╯︵ ┻━┻"
  "post-mortems"
  "Github selfies"
  "Production deployments that depend on GitHub"
  "RFC 2324"
  "Your code featured on The Daily WTF."
  "optimistic transactions"
  "Webscale"
  "Cats"
  "Ponies"
  "Your Mum"
  "Using Brain Fuck in production"
  "Picking the best color to paint your bike shed"
  "Server cages"
  "Copy-on-write"
  "deduplication"
  "LART"
  "BOFH"
  "Program Management"
  "Product Managers"
  "The Ballmer Peak"
  "0xDEADBEEF"
  "A coked-up tech recruiter"
  "A contractor that tells you it was a real learning experience"
  "RTFM"
  "A 1996 Java applet"
  "A virtual machine running a virtual machine until it brings on the Singularity"
  "Ops doing dev = technical debt"
  "#And right here, we'd like a miracle."
  "Sparkly Devops Princess"
  "Patrick Debois"
  "git merge --force"
  "A series of tubes"
  "A literal cluster fuck"
  "The library that imports all other libraries"
  "The tech lead's shitty pet project"
  "An entirely commented out file"
  "A constructor for RandomThing"
  "Circular imports"
  "A pull request with a winking smiley ;)"
  "Syntactic sugar coma"
  "Former employees who still have admin access to live production servers"
  "The ib_logfiles"
  "The mysql client"
  "Paul Graham"
  "The much neglected IPv5"
  "cron jobs that edit cron jobs"
  "Snail scale"
  "Testing positive for mongonucleosis"
  "PEBKAC"
  "ReiserFS"
  "/dev/null"
  "Little Bobby Tables"
  "Solar flares"
  "Global warming"
  "Short Stroking"
  "Reticulating Splines"
  "RAID 3 SSD cluster"
  "Re-implementing TCP over TCP"
  "Mixed endianness"
  "OAuth"
  "traceroute"
  "rockstar"
  "packet loss"
  "smokeping"
  "losing the root password"
  "Works on my machine!"
  "malloc"
  "buffer overflow"
  "StackOverflow is offline?!"
  "server logs"
  "Penetration test"
  "Deploying on a Friday afternoon"
  "Quipu"
  "too many authorization failures"
  "two single quotes"
  "kremvax"
  "the unix epoch"
  "0-day exploits"
  "tribal knowledge"
  "puppet"
  "RHEL4"
  "DevOps Reactions"
  "syntax error"
  "killall -9"
  "pre caffeine typos"
  "banana pi"
  "RAID 0"
  "PIP"
  "PyPi"
  "Synergy"
  "dev"
  "Java"
  "geometric distances"
  "Indian Ocean"
  "Out of bounds exception"
  "rm -rf /"
  "hunter2"
  "GCHQ"
  "NSA FOIA request"
  "wat"
  "kanban"
  "Halt and Catch Fire"
  "Ansible"
  "Template out"
  "bzero"
  "sendmail"
  "bare metal"
  "Slackware"
  "Bazaar"
  "runit"
  "Home-grown monitoring solution"
  "Virident"
  "ifconfig lo down"
  "Arch linux in production"
  "AUR"
  "Btrfs on a 2.6 kernel in production"
  "Actually reading the manual"
  "telnetd on the payment tier"
  "The Hungary Games"
  "the GIL"
  "Solaris"
  "SmartOS"
  "Joyent"
  "Big-endian x86"
  "Uncyclopedia.org"
  "Spongebob Squarepants"
  "Flux Capacitor"
  "Toaster on Wheels"
  "The previous developer"
  "Debian experimental in production"
  "10 years since last update"
  "HAL"
  "Testing in production"
  "The Gang of Four becoming a real gang"
  "Shoving the code down the compilers throat with catch statements"
  "Legacy Code that you're terrified of deleting"
  "That one goddamn line"
  "HTML5 vs Flash"
  "Sudo: make me a sandwich"
  "Java's Syntax"
  "The Travelling Salesman Problem"
  "Subjective C"
  "Ubuntu? I have to learn Ubuntu?"
  "Dell custumer support"
  "The Genius Bar"
  "That Goddamn Paperclip"
  "Laziness, impatience, and hubris"
  "A deleted StackOverflow post"
  "All our code becoming self-documenting because I declared it so"
  "VBScript, the future of software!"
  "The waterfall model"
  "NaN"
  "undefined"
  "An empty int"
  "Continous Testing"
  "Service Virtualization"
  "Test Automation"
  "Writing a Perl script to deploy Puppet Enterprise"
  "The OOM Killer"
  "$lastjob"
  "segfault"
  "$i++"
  "tabs not spaces"
  "spaces not tabs"
  "Spaces and tabs in the same file"
  "iptables"
  "Fedora Core 9"
  "\LaTeX{}"
  "NumPy"
  "An unmaintained man-page"
  "An old Gentoo installation"
  "TeX"
  "null-pointer"
  "Delphi code from the 1990's"
  "Turning it off and on again"
  "A PHP script comprised of shell_exec()'s"
  "A PHP script comprised of exec($_REQUEST['cmd'])"
  "Computer Science III"
  "Multiple measurement systems"
  "Date formats other than yyyy-mm-dd"
  "12 hour clocks"
  "Clocks in a timezone other than UTC"
  "Machines not running NTP"
  "Using Fahrenheit instead of Celsius"
  "Classic Vi"
  "Mesos"
  "Diva designer"
  "sudo chmod -R 777 /"
  "Concurrent Javascript"
  "NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaN Batman!"
  "Nazi Zombies!!!"
  "Netscape Navigator"
  "Mosaic"
  "Adobe"
  "Microsoft"
  "Apple"
  "Samsung"
  "A new ultrabook"
  "Binaries"
  "Scope Creep"
  "GitHub"
  "A Monad"
  "Silk Road"
  "--enable-h8"
  "--omg-optimized"
  "--funroll-loops"
  "--disable-instructions"
  "An old Solaris developer"
  "\"This webpage is not available\""
  "Dan Kaminsky"
  "65,536"
  "Being marked CLOSED WONTFIX"
  "A datacenter migration"
  "Loading the servers in the back of a shady Canadian's truck"
  "The business acumen of the Mormon Church"
  "High Latency"
  "sudo !!"
  "Defcon"
  "The training budget"
  "SUID root"
  "regex golf"
  "StackOverflow is offline?!"
  "A Monoid"
  "Slashdot"
  "quantum encryption"
  "JIRA Jr!"
  "rm -rf Russian roulette"
  "errors which disappear in debug builds"
  "javascript webservers"
  "sysadmins sneaking Minecraft on the production server"
  "reporting bugs on IRC"
  "Emacs keyboard shortcuts"
  "DevOps podcasts"
  "Hamachi for VPN"
  "debugging Genetically Programmed code"
  "Exchanging childhood memories for 160GiB of storage"
  "Saint IGNUcius"
  "--force"
  "gem native extensions"
  "anti-affinity"
  "multi factor authentication"
  "Python is the new Basic"
  "YAML"
  "Cloud-agnostic"
  "Borland StarTeam"
  "Paralax!"
  "A Python implementation that's basically just a whole bunch of C Preprocessor macros"
  "The empty string language {ε} = Ø"
  "Idempotence"
  "Chef-client running on OS/2 Warp"
  "@SwiftOnSecurity"
  "Adam Jacob's guitar"
  "PowerShell"
  "Clock skew"
  "A good scotch collection at your desk."
  "A 1:1 that goes straight to the bar."
  "A 16 hour incident bridge."
  "Something said by a NetEng that you didn't understand."
  "An obscure stack trace"
  "An app with no logging"
  "Steering the Titanic with a popsicle stick"
  "A peer that doesn't believe in peer review"
  "Angular js"
  "A former MENSA member"
  "Being acquired by Oracle"
  "More bloat than GNU code"
  "Emacs pinky problems"
  "Arguing over Java or C#"
  "Best Practices"
  "Programming drunk"
  "Custom Nagios scripts"
  "ITIL"
  "branded hoodies"
  "angel investors"
  "series B funding"
  "A noose made out of cat 5 cable"
  "A kernel hacker's beard"
  "The reaping of child processes"
  "nginx"
  "the outsourced IT department"
  "a NSFW MOTD file"
  "ASCII art"
  "bugzilla"
  "boto"
  "malicious code"
  "The return of the Y2K bug"
  "A highly sophisticated regular expression"
  "A mint-in-box AOL trial CD"
  "log aggregation"
  "The OWASP Top 10"
  "Water-scrum-fall"
  "Yet another attempt at re-writing Nagios"
  "infinite loops"
  "bareword variables"
  "rubocop"
  "A project of Stuxnet-level complexity"
  "Postgis"
  "Terraform"
  "AWK"
  "Greybeards"
  "Database antipatterns"
  "Cat5 'o 9 tails"
  "USB Type-C"
  "Just plain text"
  "HTTP 418: I'm a teapot"
  "haveToMakeMyOwnArrayIsEmptyMethodBecauseCrappyJavaDoesNotHaveIt()"
  "A client with no servers."
  "Rereading code of last night"
  "Debugging 500 lines of code per method. Average."
  "localhost"
  "It doesn't happen on my machine"
  "Unit testing randomization"
  "Dropping tables on a Friday"
  "Literally driving development"
  "while(true)"
  "Using a switch for a boolean"
  "ENUM('Y','N');"
  "Mac OSX"
  "Replacing all dev machines with Raspberry Pis"
  "Redirecting www to dev"
  "The Cloud"
  "1337"
  "Minorities in tech"
  "Another Wordpress vulnerability"
  "A Raspberry Pi botnet"
  "DDoSing 127.0.0.1"
  "Low Orbit Ion Cannon"
  "Script kiddies"
  "Hack Forums"
  "/r/talesfromtechsupport"
  "@sadserver"
  "Little Bobby Tables"
  "Downtime"
  "Unixbeards"
  "Excessively long variable names"
  "A parent killing its children"
  "Zombie processes"
  "Commenting every line of code"
  "DEFCON"
  "Richard Stallman"
  "Emojis as identifiers"
  "Trolling the sysadmins"
  "Running Java 6"
  "UNDO UNDO UNDO"
  "Hypertext Coffee Pot Control Protocol"
  "IP Over Avian Carriers"
  "SONET to Sonnet Translation"
  "IP Over Avian Carriers with QoS"
  "SCCS"
  "Infinite Monkey Protocol Suite"
  "National Security Letter"
  "Hyper Text Coffee Pot Control Protocol for Tea Efflux Appliances (HTCPCP-TEA)"
  "NSA (No Secrecy Afforded) Certificate Extension"
  "Scenic Routing for IPv6"
  "Really Explicit Congestion Notification (RECN)"
  "Internet Explorer"
  "Silk Road"
  "The Tor Network"
  "sudo rm -rf /"
  "COBOL"
  "/dev/random"
  "Windows ME"
  "Windows for Workgroups"
  "M-x dwim"
  "===== operator"
  "kibo"
  "Elvish"
  "Klingon"
  "Na'vi"
  "XSLT"
  "A blue box"
  "APL"
  "Snobol"
  "Bogosort"
  "The Jargon File"
  "AI-complete"
  "BCPL"
  "?= operator"
  "12 hamsters"
  "Selenium"
  "A server with no client"
  "Trusting User Input"
  "Guru Meditation"
  "Unexpected T_PAAMAYIM_NEKUDOTAYIM"
  "402: Payment required"
  "Treating warnings as errors"
  "Turning up to work still drunk from yesterday"
  "Private members"
  "EgoDB"
  "LISP"
  "r/talesfromtechsupport"
  "git push --force"
  "A pi stack"
  "PBKAC"
  "Reddit"
  "A poorly abbreviated function name"
  "#nosemver"
  "The .sucks Domain"
  "The <blink> tag"
  "The <marquee> tag"
  "CTRL - C! CTRL - C! CTRL - C!"
]
module.exports = (robot) ->

  robot.respond /devops card( me)?/i, (message) ->
    message.send draw_cards()

draw_cards = ->
  black_card = black_cards[random_index(black_cards)].split(' ')
  for word in black_card
    if word.match(/_{10}/)
      black_card[_i] = white_cards[random_index(white_cards)]
  black_card.join " "

random_index = (array) ->
  Math.floor(Math.random() * array.length)
