module.exports = [
    "__________ logs or it didn't happen."
    "__________, for some values of __________."
    "Ask Me Anything about __________."
    "Called on account of __________."
    "Disrupting the established players in __________ via __________."
    "Doge __________."
    "Employees must __________ before returning to work."
    "Enterprise __________ in the cloud."
    "Enterprise-ready __________."
    "Epic yak-shave caused by __________."
    "Facebook has acquired __________ for $10b and __________."
    "Free as in __________."
    "Glitter-bombed with __________."
    "Hi, I'm Troy McClure. You may remember me from such commit messages as __________ and __________."
    "How is __________ even formed?"
    "I can haz __________."
    "Tinder for __________"
    "I saw the best minds of my generation __________."
    "If __________ is the answer, you are asking the wrong question."
    "If you're using __________, you're gonna have a bad time."
    "Nobody ever got fired for buying __________."
    "Running Windows in production leads to __________."
    "The Internet is for cat memes and __________."
    "Our release schedule doesn't have time for __________."
    "The Internet of Things will be controlled by __________."
    "The only thing necessary for evil to triumph is __________."
    "Uber is on surge pricing because of __________."
    "WARN: __________ has been deprecated."
    "Will merge pull requests for __________."
    "Zero-day __________."
    "Time to schedule the postmortem for __________."
    "__________ - the idiots guide to __________ and __________."
    "Put some __________ on it!"
    "Wrap it with the __________ duct tape."
    "But Google is using __________ so we should too!"
    "__________ is the new __________."
    "Etsy says we should __________ everything."
    "xkcd.com just made a hilarious comic making fun of __________."
    "This isn't going to be all unicorns and __________."
    "Apple just patented __________."
    "When I was a kid we didn't have __________."
    "__________ is a nice idea, lets found a start-up."
    "DevOps: Now with 100% more __________!"
    "Main benefits of automation: __________ and __________."
    "Chef converge failed due to __________."
    "Then there was the time I found __________ on the root partition."
    "We run production on __________ and __________."
    "Management said it's OK to deploy __________ at 5pm on Friday."
    "Did you know that we have __________ on pager rotation?"
    "There was no good solution for __________, so we built our own using __________."
    "Amazon built a data enter on the moon to lessen the risk of __________ causing problems."
    "In order to improve security, we're upgrading to __________."
    "The two pillars of our Continuous Deployment pipeline are __________ and __________."
    "I got paged at 3am because of __________."
    "The most stable part of our infrastructure? __________. For sure."
    "When I told Jez Humble about our __________, he actually cried."
    "When I write a book about my experiences, it'll be called \"__________, the good parts\"."
    "Restoring from backups failed due to __________."
    "My two most indispensable tools are __________ and __________."
    "The production data center burned down because of __________."
    "It turns out that the button labeled \"Don't Push\" actually does __________."
    "You should think of your servers like __________ and not like __________."
    "I find Java to be way too __________."
    "It's like trying to herd __________."
    "I ended up having to buy a replacement __________ on eBay."
    "__________ is more memory than anyone will ever need on a computer."
    "__________ Driven Development."
    "The RIAA is suing me for downloading __________."
    "Security? We've got that! We use __________."
    "sudo pip install __________"
    "When I hooked the 3D printer up to the Internet, it accidentally created __________."
    "My next blog post will be about how we used __________ to create __________."
    "So, I was using Wireshark to check network traffic... Did you know we have __________ in production?"
    "My eyes started bleeding when I opened the editor and saw __________."
    "I think maybe I'll leave __________ off my resumé."
    "We don't need __________ - we have __________ !"
    "Management just told me I need to get certified in __________."
    "Our app is like __________, but for __________."
    "Marketing says we're leaders in the __________ space, but I think it's more accurate to say we specialize in __________."
    "Our greatest achievement in the last year is __________."
    "I write my code in vim because of __________."
    "If we make this deadline, management has promised us __________."
    "Sweet! I just found a Puppet module for __________!"
    "Last week, I created a Chef recipe for __________; this week, it's an entire cookbook for __________, Automation FTW!"
    "We really need to open-source our __________."
    "A sales rep just tried to pitch me on __________; I told them we already have __________."
    "Who would have known that __________ could destroy an entire datacenter?"
    "sudo apt-get install __________"
    "Our production backups are stored using __________."
    "We replaced our __________ with __________."
    "After __________ came up, the retrospective really went downhill."
    "You know what our app needs? More __________, and less __________."
    "It figures - an article about our __________ was posted just as we're pivoting to __________."
    "In the next planning session, we'll cover __________ and __________."
    "Our competitive advantage is our __________."
    "Every time someone brings up __________, I throw up a little in my mouth."
    "Continuous __________."
    "All that we had to do to halve our response times was implement __________."
    "Our entire app is geared towards providing __________."
    "__________-ility"
    "We just achieved __________s per second!"
    "__________ is that even HA?"
    "My LinkedIn endorsements include __________."
    "__________ just endorsed me for __________ on LinkedIn"
    "Users are __________."
    "Robots are going to make __________ obsolete."
    "Accidental __________."
    "An error occurred: __________"
    "According to the logs, __________ was initially caused by __________."
    "We can just fix that with a little __________."
    "You can have __________, __________, or __________.  Pick two."
    "A monad is just a __________ in the category of __________, what's the problem?"
    "Functional programming - if you can't __________ it, __________ it."
    "On a scale from 1 to 10, this is __________!"
    "We don't need configuration management, we have __________!"
    "__________, now with __________ support."
    "RedHat has announced that RHEL 8 will ship with __________."
    "Hey, __________ is down. Can you fix it?"
    "I grabbed __________ on my way out the door after our paychecks bounced and management stopped answering their phones."
    "Did you try __________ yet?"
    "I was 6 beers in when I got the pager alert that __________ was down."
    "Notice: Building __________ for __________"
    "I laughed when they said I'd be on call 24/7 but wouldn't receive a stipend for __________."
    "If it weren't for __________ we'd all be __________."
    "__________, __________ and just a few lines of Perl."
    "NoSQL is superior to SQL because __________"
    "Script kiddies got into __________ because __________."
    "__________ is better than Hadoop because __________."
    "Rub a little __________ on it."
    "WAIT, YOU DELETED __________??!"
    "@__________borat"
    "It's not web scale, it's __________."
    "The tech support hotline told me to __________."
    "Asynchronous REST API calls are the solution to __________."
    "Say concurrent threads again and I will __________ you."
    "Guys, seriously, if we just use __________ it will solve all our problems with __________!"
    "Facebook changed their profiles today because __________."
    "github.com/__________/__________"
    "Hello. My name is __________ and I am addicted to __________ ."
    "__________ dependency hell."
    "That talk outline said it would be about __________, but it ended up being more like __________."
    "I will replace you with a very small __________."
    "Jordan Sissel hates __________ so much that he created a new opensource project called __________ to work around it."
    "__________ isn't a job title."
    "For the next project we are going to use __________ to solve __________."
    "My editor of choice is __________."
    "__________ it; ship it."
    "__________-Stack Developer"
    "__________SQL"
    "It has been __ days since the last __________"
    "The __________ on the server were deleted because __________."
    "This week, Aphyr runs __________ through jepsen."
    "The intern just ran __________ on the load balancer."
    "I need you to do a __________ with __________ before __________."
    "Lambdas are just a lame implementation of __________."
    "C-x; C-__________"
    "This users wants __________ because __________."
    "__________ should be deprecated in favour of __________."
    "__________ mismatch between __________ and __________."
    "I put __________ on the scripts to make it run faster."
    "Developers do not get access to production machines, because of __________."
    "Developers need access to production machines because __________."
    "We run __________ in a cron job every 15 minutes."
    "The client says it needs more __________ ."
    "We're a __________ as a Service company."
    "I could hire a __________ to do your job!"
    "My next Velocity talk is called \"__________ops\""
    "The RCA for the global outage was __________ compunded by __________."
    "I was hired to maintain this 20 year old script that runs our critical __________ infrastructure."
    "Amazon Elastic __________"
    "I know we use __________, but I wrote this critical program in __________."
    "I'll just have Ops spin up a couple of __________ environments."
    "I'm writing my next IRC bot with __________."
    "I cannot wait until someone makes a __________ cluster out of these."
    "C will finally be displaced by __________."
    "We don't need to worry about __________, we're using MongoDB."
    "Why is __________ better than Hadoop?"
    "FC067: __________"
    "Oh, the __________ is just a hack to get the __________ to run."
    "How do I even __________?"
    "__________ all the things!"
    "ERROR: __________ NOT FOUND"
    "We don't need backups, we've got __________."
    "Fixing your father's computer with __________."
    "It's always a __________ DNS problem."
    "__________ with this one weird trick."
    "__________ isn't new, we used to do it in the '70s on mainframes."
    "Puppet is better than Chef because __________ and __________."
    "How is __________ better than __________?"
    "Learn __________ the hard way."
    "Vagrant up __________."
    "Bollocks up __________."
    "You can fix  __________ with __________ ."
    "We took the plunge and rewrote __________ in Go."
    "Implementing __________ should take only 2 lines of code."
    "Good enough for __________ work."
    "Yeah, but can it run __________?"
    "Security through __________."
    "__________? You can safely ignore that. Usually."
    "__________ isn't cool. You know what's cool? __________."
    "I made a new editor, better than vim and emacs. It's called __________."
    "640k should be enough for __________."
    "__________ worked in dev."
    "You can't fix __________."
    "How hard could it be to port Linux to __________."
    "I just finished working on my rocket powered __________."
    "Richard Stallman will kill you with his teeth for __________."
    "DB tuning with __________."
    "Can anyone help me get __________ running on Cisco IOS?"
    "Real __________ don't use __________."
    "__________ on XEN."
    "Please bring back __________. You broke my workflow."
    "I cut-and-pasted this StackOverflow code for my __________."
    "I'm just finishing up my manifesto on __________."
    "r/__________."
    "We can discuss __________ at the stand-up meeting."
    "A Beowulf cluster of __________."
    "We're demoing __________ for __________ at SXSW."
    "I aliased __________ to git __________."
    "10 PRINT \"__________\"; GOTO 10"
    "alt.binaries.__________"
    "It is completely dark. You are likely to be eaten by a __________."
    "Conway's Game of __________."
    "Next year I'll start learning __________."
    # "s/__________/__________/g" # TODO: Fix this.  Its awesome, but doesn't work.
    "__________ is the newest gTLD."
    "Works on my __________."
    "One does not simply __________."
    "Sorry, you'll need to open a ticket before we can __________."
    "ln -s __________ __________"
    "__________ is dead."
    "__________. WTF does that even mean?"
    "Make it __________."
    "__________coin"
    "__________ computing"
    "grep __________ | mail __________"
    "__________ just got pwned."
    "It's like __________, but with __________ and list comprehensions."
    "Software defined __________."
    "I don't have any UNIX Beards in stock, but we do have __________."
    "Amazon does __________, why can't we?"
    "__________ nagios"
    "I can't believe you're still using __________."
    "/dev/__________: Device is busy"
    "__________, You don't exist, go away!"
    "I tried __________, the doctors say I'll never walk again."
    "git --__________"
    "The __________ Public License."
    "__________ begins with __________."
    "Couldn't we use __________?"
    "__________ would be so much better if we rewrote it in Clojure."
    "So I just found __________ and __________ running in a screen session."
    "Why is root running __________ under tmux?"
    "Instead of installing __________, what if we just used __________."
    "I need a webinar like I need __________."
    "Fuck it, time to break out the emergency __________."
    "On the plus side, we finally got rid of __________."
    "__________ thought leader."
    "Fuck it: __________ looks good to me."
    "It looks like you're trying to __________. Can I help?"
    "zsh: command not found: __________"
    "How did __________ ever work?"
    "Whoops, I thought that method was supposed to __________ the __________."
    "I thought you said __________ was secure?"
    "git: You are in detached __________ state."
    "Why don't we just fork __________?"
    "Network dropped connection because of __________."
    "We turned off __________ and everything magically got better."
    "I found a Samba share full of __________."
    "__________. What could go wrong?"
    "Install __________."
    "I installed __________ by accident."
    "Read-eval-__________-loop."
    "We should try it with an actual __________."
    "Is __________ something we need to optimize for?"
    "Hack __________ into redis."
    "__________ considered harmful"
    "Never __________ before a demonstration."
    "The __________ is used when the CPU is on fire."
    "modperl can be used to implement __________."
    "__________ runs Ruby as root."
    "Larry Wall trained as missionary then __________."
    "Listening to the fans in the server farm leads to __________."
    "__________ and __________ are rumoured to be working on a python module for a helicam."
    "A lot of disk space is needed for __________."
    "automagical __________"
    "Whoever made the unscheduled change to production on Friday will be forced to use __________."
    "Never question the __________."
    "I can't wait until we no longer use __________."
    "I bet if we switch to __________ it will just work."
    "__________ has just discovered __________.  We're doomed."
    "A neckbeard made of __________."
    "False alarm, it was just __________ running __________."
    "__________ running on a rack of __________."
    "No, __________ being hopelessly broken is NOT an emergency."
    "Our new startup is the __________ for __________."
    "__________ make me a sandwich."
    "__________ over IP"
    "__________ is a hardware problem."
    "I AM working, I'm waiting for __________ to finish."
    "The first rule of __________ is: You do not talk about __________."
    "Google Analytics says 100% of my website visitors are __________."
    "__________ will never get you a job at Microsoft."
    "4chan.org is powered by __________."
    "We can __________ just like Netflix."
    "__________ is how I resolve all merge conflicts."
    "Why does someone keep re-implementing system utilities in __________?"
    "Remember when you told me to tell you when you were acting __________ and __________? You're doing it now."
    "Our only hope at recovering the data is __________."
    "__________: the gift that keeps on giving."
    "__________ has been killed with fire.  My work is done here."
    "Problem exists between keyboard and __________."
    "100% government funded __________!"
    "The __________ certification program."
    "I just finished writing an API for __________."
    "__________ is a batch command to shut the heck up."
    "__________.  Failed to cache catalog."
    "Everytime you allocate you have to __________ when you're done."
    "Sorry, I'm all out of __________-fu."
    "90% of everything is __________."
    "Given enough __________, all bugs are __________."
    "__________ never use on git"
    "The first 90% of development is __________. The second 90% is __________."
    "When you logged in there, did you see a __________ that said __________?"
    "Purely numeric hostname and not a __________ -----rejecting!"
    "I'm pretty sure __________ isn't thread safe..."
    "We don't have to worry about CAP Theorem because of __________."
    "I don't always test my code, but when I do I do it in __________."
    "Those who don't understand __________ are condemned to reinvent it, poorly."
    "The NSA is really interested in our latest project: __________."
    "Just change the __________, it'll be fine."
    "Yeah, you need to modprobe __________ to get it to recognize the __________."
    "Oh, we're devops! We have __________ in the office, but only the DBA can touch it."
    "We're spending 20% of this sprint doing __________."
    "__________ found a new OpenSSL vulernability people are calling __________."
    "Management has changed all our job titles to __________."
    "while true; do __________; done"
    "The consultant we hired is certain that __________ will drastically increase the performance of __________."
    "Could you just push this update for __________?  It should be a no-op."
    "If we're all going to get fired, let's get fired for __________."
    "We can't pay you, but we can offer __________ in compensation."
    "A soiled napkin with the contents of __________ scribbled on it."
    "Who thought that __________ was a good idea?"
    "It's not the recommended configuration to use __________ with __________, but it's in production right now."
    "We wrote our own build tool based on __________."
    "I've received a Microsoft MVP award for __________."
    "We rewrote __________ in __________."
    "The ticket to install __________?  I deletegated it."
    "Some people, when confronted with a problem, think \"I know, I'll use __________.\" Now they have two problems."
    "Artisanally crafted __________."
    "The backups are fine, but the restore process is __________."
    "I can't believe QA filed a bug for __________."
    "The __________ that ops provides developers."
    "Oracle is proud to announce that the next edition of Java features __________."
    "Move __________ and break things."
    "__________: ci or not ci?"
    "I opened the server cabinet and it was full of __________."
    "Crossing __________ could lead to total protonic reversal."
    "The next big thing is __________."
    "I once made a robot around the concept of __________."
    "I __________ your stupid issue!"
    "Nine circles of __________ hell."
    "I once wrote an NPM module called __________.js"
    "I asked the contractor for __________ and they delivered __________."
    "Welcome to Programming 101, our first topic will be __________."
    "The Genius Bar recommends you try __________."
    "Post-modern coding is defined by __________."
    "__________ | sudo sh"
    "__________ has been put under the WTFPLicense."
    "Here's __________, as I promised."
    "I'd like __________, __________, and a Fluttershy."
    "It transpiles __________ to JavaScript."
    "Only the Enterprise Edition™ has __________."
    "__________ is a proof of concept and an actual __________ __________."
    "The trouble with kids these days is __________."
    "__________ is the new Stalinism."
    "__________ for the win!"
    "__________ is the new __________."
    "Don't read the __________ or the __________ pages."
    "With __________, you write once, run nowhere."
    "__________ discontinued support for the Linux version."
    "A manager told me I couldn't remove our dependency on __________, but I got around it with __________."
    "__________ implements every single standard for __________.  Poorly."
    "Just think of the Internet as __________."
    "Would you like __________ with that?"
    "__________? We've got that."
    "It took over 40 hours to document __________. "
    "//TODO: __________."
    "npm install __________."
    "Circular imports import __________. "
    "A firewall rule for __________."
    "__________ is why the jDBA thought it might be time to go to #mysql on freenode"
    "__________ is the only reason the jDBA survived typing rm -rf /"
    "__________ exists?"
    "It's like __________ on __________."
    "I came here to drink milk and __________, and I've just finished my milk."
    "End-to-end __________."
    "__________ will help you remember to sanitze your database inputs."
    "Fascists cannot stand __________."
    "RTFM so you can __________."
    "__________ took EBS down again today."
    "I ssh'd into a server running __________ and promptly noped the fuck out of there."
    "__________, the final solution."
    "We're running __________ in production?!"
    "__________ has root access."
    "We don't have enough package managers, said __________."
    "__________ is more reliable than __________."
    "Of course culture is important to us, that's why we have __________."
    "I'd trust all my stuff to __________."
    "My __________ for a __________."
    "Nice __________ I'll take it."
    "@horse__________"
    "Such __________. Wow."
    "That's funny, did __________ used to be here?"
    "I can't believe you improved __________ by deleting __________."
    "The only thing more dangerous than __________ is a programmer with __________."
    "1. __________     2. __________    3. Profit."
    "Monads are easy! Just think of them as __________"
    "__________: powered by the cloud."
    "I upload my worm to __________"
    "#!/bin/__________"
    "make __________ && sudo make install && cowsay yay"
    "I bet the person who wrote this uses __________."
    "I'm not __________, my code is compiling."
    "Don't worry, we have unit tests for __________."
    "As a __________, I want __________."
    "The only non-conformance in this year's audit was __________."
    "We're blaming interns for the __________."
    "__________ is my favourite thing about __________."
    "I wish that we had more __________ in our office."
    "I've once been so drunk that __________ actually made sense."
    "To understand __________ you must first understand __________."
    "__________ @ 127.0.0.1 -p __________"
    "__________? You mean __________!"
    "__________ is coming out of stealth mode."
    "__________ ate all my memory"
    "__________ is always a good practice."
    "Don't mind me, I'm just practicing __________."
    "We accidently the whole __________."
    "It's easy! Just run __________."
    "I assure you __________ is secure!"
    "Our backup policy is __________."
    "pacman -Syu accidentally __________ everything"
    "I saw a high availability blog post about __________."
    "We didn't think anyone was using __________!"
    "Do you wanna build a __________?"
    "IBM just created JSONxx to encapsulate JSON in XML in __________."
    "I never truly understood eXtreme programming until I encountered __________."
    "The Agile Manifesto taught me to pick __________ over __________."
    "__________ should be a singleton!"
    "Flash is dying because __________."
    "Neo, the matrix has one fatal flaw, you must find __________."
    "Javascript is the best language ever, thanks to __________."
    "Last night while drunk, the W3C declared __________ as a new web standard."
    "North Korea finally launched warheads because of __________."
    "Last night I accidentally ran sudo chmod -R 777 /. I just blamed __________."
    "During the lunch break I like to think about __________."
    "Nobody will value your work if you don't use __________."
    "__________, because scientists don't know how to code."
    "__________, because Knuth."
    "The entire system failed because of __________."
    "The meeting between Europe and the USA was cancelled because of __________."
    "We missed the launch window due to confusion from __________."
    "__________ wasted thousands of dollars."
    "No one can authenticate because of __________."
    "__________ caused the servers to melt down."
    "__________ invalidated all the assumptions in our monitoring system."
    "__________ because __________."
    "CAMS is outdated because of __________."
    "__________: Easy one-step installation"
    "__________, because even the hobos of Market Street need a cluster scheduler."
    "We need to update the __________."
    "It's cool, they use __________ at Etsy."
    "Code as __________."
    "__________ is how the cloud works."
    "How does it look in Opera?"
    "The __________ shell"
    "__________ in haskell"
    "Say __________ one more time; I dare you!"
    "The cloud runs on __________, with a bit of __________."
    "__________, because who needs monitoring. "
    "This problem can be completely solved with __________ implemented in __________."
    "__________ vs __________... FIGHT!"
    "I regret to inform you your weekend has been revoked due to __________."
    "All alerts go to __________, which is handled by __________."
    "__________, it's the new pink."
    "I've got 99 problems but __________ ain't one."
    "140 characters is just enough to explain __________."
    "__________ all the way down."
    "__________ continuously spawns zombie processes."
    "Elliptic-Curve Diffie-Helman breaks against __________."
    "Why isn't my script working? Oh. __________."
    "ITIL best practices suggest __________ is the next step."
    "We would have gotten the funding, if only our slide deck included __________."
    "Have you tried __________ and __________?"
    "I left __________ in the server room."
    "I stuck my hand in a sysadmin's beard and pulled out __________."
    "Before exiting, the program kills __________."
    "Cookbooks containing __________ have been known to cause __________."
    "Once we added __________ to the firewall rules, __________ worked perfectly."
    "My pre-commit hook replaces tab characters with __________."
    "I was up all night debugging __________."
    "Error: insufficient __________"
    "The Product Team handed me a spec, they want __________ in the next release of __________."
    "The malware came from an infected ad on __________.com"
    "Killing child processes releases resources back to __________."
    "That regular expression is designed to match __________ but not __________."
    "The vendor solution didn't have log aggregation, but it did have __________."
    "Our custom log rotation scripts have the added feature of __________."
    "This year, Cross-Site Request Forgery was knocked out of the OWASP Top 10, and replaced by __________."
    "Nagios sucks, let's replace it with __________."
    "My pull request was rejected because it contained __________."
    "My stacktrace revealed __________."
    "Chef encountered an error attempting to create __________."
    "Since the 1950s, engineers have been striving toward a more effective means of generating __________."
    "Our code was efficient, except for the module containing __________, which was slower than __________."
    "I need to re-munge the CSV, replacing the commas with __________."
    "We strive for continuous deployment, continuous delivery, and continuous __________."
    "Data-driven decisions are to be replaced with __________."
    "The ruby gem is useless, it's a lesser implementation of __________."
    "Windows ME had a service pack that solved the problem of __________."
    "Lennart Poettering's latest project is __________."
    "__________ is the quickest way to identify what is burning in the server room."
    "Oh, we store all our docs in __________."
    "I accidentally __________ the whole database."
    "It's not a bug it's a __________."
    "What killed the mood at E3?"
    "To replace camelCase, the new C++ standards mandate variables be named using __________."
    "I'm sorry __________ isn't numberwang."
    "I'm sorry __________ isn't wangernum."
    "__________ became self aware and kidnapped the sysadmins."
    "That's the first time I've ever seen ProGuard used to obfuscate __________."
    "Every day at work I implement __________ and my mother still tells her friends I \"do computers\"."
    "That's the first time I've ever seen comments written in __________."
    "It's not a problem, I'll just __________ it later."
    "I, for one, welcome our new __________ overlords."
  ]
