module.exports = [
  "the Cult of Mac"
  "fuckedcompany.com"
  "Golang"
  "growth hacking"
  "Larry Ellison"
  "leaky abstractions"
  "meritocracy"
  "MongoDB"
  "Node.js"
  "NPM"
  "Pareto Inefficient Nash Equilibriums"
  "posting on Etsy's codeascraft blog"
  "Python datetime module"
  "rebasing the entire fucking repo"
  "518: recruiter failure"
  "Ruby"
  "running out of IPv4 addresses"
  "sysadmins"
  "the Stanford of Canada"
  "thought leadership"
  "Twitter"
  "Unicode errors"
  "unknown source in your stack trace"
  "waiting for console.aws.amazon.com"
  "women in tech"
  "yet another package manager"
  "our release engineer"
  "OpenSSL"
  "Heartbleed"
  "the NSA"
  "O'Reilly"
  "Edward Snowden"
  "Google"
  "Magic Spray"
  "web scale"
  "functional programming"
  "stack trace generator"
  "100 enigineers crying out \"PHP? Oh dear god why?!\""
  "SVN"
  "Perl 6"
  "COTS Shareware"
  "a 2400 baud modem"
  "a squirrel with a taste for fiber"
  "zombie processes"
  "CAP Theorem"
  "a snowflake server"
  "a Cisco router with a flaky chip"
  "NullPointerException: null"
  "Apache 1.2 running as root"
  "more buzzwords than you can shake a scrum at"
  "VisualBasic DLLs"
  "a JAR full of spaghetti"
  "an epic caffeine bender"
  "a WSDL from 2003"
  "the Sales & Marketing department"
  "business logic in PowerPoint slides"
  "/var/log symlinked to /dev/null"
  "hypervisors running hypervisors running hypervisors"
  "an angry badger with an electromagnet on its back"
  "a shared root password"
  "private keys in /var/www"
  "parsing HTML with regex"
  "a 3.5\" floppy disk"
  "an untested restore process"
  "a cron job that reboots the server every 5 minutes"
  "Apache Zookeeper on a 286"
  "sadness as a service"
  "cloud-based business strategy"
  "the next Y2K"
  "an army of chaos monkeys, all carrying flamethrowers"
  "a CORBA service written in Ada which communicates using JSONx"
  "a home-rolled systemd replacement"
  "a custom kernel with Frontpage Extensions installed"
  "a mobile web 2.0 RIA"
  "agony-driven development"
  "being acquired by Oracle"
  "catastrophic failure as a service"
  "10,000 Nagios alerts per second"
  "a global write lock"
  "75-tier architecture"
  "hand-crafted artisan x86 assembly code"
  "the world's only fully-functional ROFLcopter"
  "a proof that P=NP written in BASIC"
  "an Exchange email loop"
  "a Volker-Craig terminal"
  "a self-aware PHP script"
  "a 500-megabyte UDP packet"
  "the last remaining Multics server on Earth"
  "a Null-modem cable"
  "a turducken made entirely of bash scripts"
  "write-only code"
  "PagerDuty configured with a random number generator"
  "Netscape Navigator 3.2 support"
  "dd"
  "a Piñata full of error messages"
  "mutation of immutable data"
  "Maven downloading the entire internet"
  "continuous disintegration"
  "IE6"
  "Magic Smoke"
  "done done"
  "tech debt day"
  "log shipping"
  "uucp"
  "the 4chan party van"
  "Adderall"
  "Tcl"
  "NoOps"
  "an angry whale shitting containers"
  ":(){ :|:& };:"
  "too big data"
  "freebasing caffeine"
  "mainlining caffeine"
  "a fat fingered tech manager"
  "half open TCP connections"
  "Steve Ballmer wielding a battleaxe"
  "a 50k line Bash script that's achieved self awareness"
  "Gigadevops"
  "enterprise grade Bash scripts"
  "agile"
  "a pink sombrero and a fifth of tequila"
  "a simple 15 level Hiera hierarachy"
  "lolscale"
  "CouchDB"
  "GeoCouchDB"
  "high availability"
  "Map-Reduce"
  "Erlang"
  "a non-ironic BSOD"
  "ntpdate"
  "12 factor applications"
  "fail early, fail often"
  "that one xkcd about regexes"
  "a violation of the most basic engineering principles"
  "the BOFH"
  "a water buffalo"
  "a routing loop"
  "a queue with no consumers"
  "Bitcoin mining"
  "a firewall full of holes"
  "an uncontrollable deluge of emails"
  "the tech manager saying, \"I heard about it on Hacker News\""
  "Ycombinator"
  "a jailbroken iPad"
  "Vagrant"
  "Nokogiri Gem"
  "Docker"
  "a \"MRW\" animated gif"
  "$HOME/.gem"
  "a posting on Craigslist \"internet engineers\" jobs forum"
  "ssh in a for loop"
  "a cold cup of coffee"
  "destroying your tools with your tools"
  "UTF-9"
  "a dozen vendor t-shirts"
  "an unlimited data plan"
  "UTF-7"
  "out-of-band access"
  "sudo rm -rf /"
  "a series of tiny shellscripts"
  "Dogecoin"
  "kernel panic"
  "Hugops"
  "lolcats"
  "culture"
  "percussive maintenance"
  "IE 7 Support"
  "Hangops"
  "Unix philosophy"
  "trying to install MongoDB on AIX 3"
  "a server rack full of crushed dreams"
  "Monads"
  "silos"
  "elastic load balancers"
  "RFC1178"
  "full-stack developers"
  "Andrew Clay Shaffer"
  "Jordan Sissel"
  "a new printer"
  "a potato"
  "Office Space"
  "Git blame"
  "Steve Balmer chanting \"Developers! Developers! Developers! Developers!\""
  "single stepping through the kernel"
  "de-linting source code"
  "significant whitespace"
  "a series of tubes"
  "secret sauce"
  "a commit consisting entirely of \"# What is this used for?\""
  "regular expressions"
  "git blame on \"# FIXME: For now, just don't validate\""
  "ASAP"
  "the Goddamn CDN"
  "authentication and authorization"
  "a cluster of applications on a cluster of servers"
  "beating the server into submission with your bare hands"
  "read-only Fridays"
  "/r/sysadmin"
  "distributed computing"
  "sprint planning"
  "merge conflicts"
  "unplugging a server and waiting to see who complains"
  "a tiny ounce of knowledge"
  "too big to fail"
  "NoQA Movement"
  "a few instances"
  "operations hipsters"
  "cowboy developers"
  "a cubism farm"
  "HipChat"
  "an IRC bot written entirely in sed"
  "(╯°□°）╯︵ ┻━┻"
  "developers saying \"worked fine for me\""
  "a torrent of Torrenters torrenting"
  "COBOL"
  "in b4 FIRST"
  "Donald Knuth"
  "rebooting all the things"
  "running Openstack in production"
  "the Berkshelf way"
  "DNS"
  "SIGHUP"
  "animated GIFs"
  "PC LOAD LETTER"
  "automating all the things"
  "delightful"
  "cache invalidation"
  "proxy errors"
  "an online book seller"
  "dust bunnies"
  "Pete Cheslock"
  "networking"
  "a sad log with a mustache"
  "blue screen of death"
  "ISO 8601"
  "Daniel J. Bernstein"
  "Linus Torvalds"
  "Broadcom chipset"
  "Moe"
  "that XKCD comic about sysadmins"
  "iso 8859"
  "RFC 1149"
  "a pimply faced youth with nothing to lose"
  "Theo de Raadt yelling at newbs"
  "hate driven development"
  "Lotus123"
  "IPSec"
  "hackathons"
  "GNU/Linux"
  "ZeroVM"
  "stringing cloudtobutt.pl into postfix"
  "ZeroMQ over SSH"
  "SQLite"
  "LevelDB"
  "leap second bug"
  "the fucking JVM"
  "continuous deployment"
  "numactl"
  "zsh"
  "standing around outside on the streets of SOMA with an overheating laptop drunk while fixing your god damn Saturday night deployment"
  "vegan friendly init scripts"
  "committing from the bar"
  "servers that follow daylight savings time"
  "rolling Grubhub into the build failed script"
  "command line options"
  "temporary hotfixes"
  "jsLinux"
  "SIGKILL"
  "your private browsing history"
  "top"
  "arguing over the internet"
  "the year 2038"
  "pdisk"
  "rsync"
  "CFLAGS"
  "cowsay"
  "profanity in the git log"
  "Gentoo"
  "the CEO"
  "ping pong"
  "Dennis Ritchie"
  "PAM happy hour"
  "complex systems usually operating in failure mode"
  "FAT32"
  "winsock"
  "fork() on Windows"
  "runlists"
  "echo shell_exec(\"sudo ./smbkill \".escapeshellcmd($_GET['kill']).\" 2>&1\");"
  "kill -9 -1"
  "curl 4chan | sudo sh"
  "HTML9 Responsive Boilerstrap JS"
  "neckbeards"
  "a certified SCRUM Master"
  "bus error"
  "git reset --hard origin/master"
  "force pushing to master"
  "Paxos"
  "LogFiles\W3SVC1"
  "a German installation of Windows NT4"
  "curl | sh -c"
  "OpenLDAP"
  "Spot Instances"
  "those ksh scripts"
  "/cgi-bin/php5"
  "a $60 QNAP and some positive thinking"
  "raspberryPI"
  "Windows ME"
  "@echo off"
  "Active Directory"
  "conflict minerals"
  "continuous incineration"
  "the gentle sound of weeping drifting from the server room"
  "eventual consistency"
  "Microsoft® Azure"
  "pinging the broadcast address"
  "that moment when you realize CTRL-Z cannot save you"
  "127.0.0.1"
  "ethernet"
  "IPv6"
  "re-writing deployment scripts at 2 AM"
  "piping /var/log/messages to Twitter"
  "a pseudorandom number generator"
  "an outage window"
  "Sentinel System Driver"
  "fpm"
  "catastrophic cancellation"
  "termcap"
  "f00d"
  "one giant SPOF"
  "Richard Stallman's neckbeard"
  "phpMyAdmin"
  "righteous anger"
  "/etc/hosts"
  "CEOs with root access"
  "automagic metaprogramming"
  "re-implementing TCP over UDP"
  "segfault"
  "#define BEGIN  {"
  "Microsoft Access over a WAN"
  "git submodules"
  "Haskell"
  "functional reactive"
  "memegen"
  "Flynn"
  "eventual persistence"
  "Jenkins"
  "bingo balls"
  "mechanically recovered turkey"
  "ChatOps"
  "Scala"
  "Trello board"
  "mechanically recovered data"
  "Friday afternoon deployment"
  "YoloDB"
  "piping random scripts from the internet into bash"
  "post-mortems"
  "Github selfies"
  "production deployments that depend on GitHub"
  "RFC 2324"
  "your code being featured on The Daily WTF"
  "optimistic transactions"
  "Webscale"
  "ponies"
  "using Brain Fuck in production"
  "picking the best color to paint your bike shed"
  "server cages"
  "copy-on-write"
  "deduplication"
  "LART"
  "program management"
  "product managers"
  "the Ballmer Peak"
  "0xDEADBEEF"
  "a coked-up tech recruiter"
  "a contractor that tells you it was a real learning experience"
  "RTFM"
  "a 1996 Java applet"
  "a virtual machine running a virtual machine until it brings on the Singularity"
  "ops doing dev = technical debt"
  "finding \"#And right here, we'd like a miracle.\" in the source"
  "a sparkly devops princess"
  "Patrick Debois"
  "git merge --force"
  "a literal cluster fuck"
  "the library that imports all other libraries"
  "the tech lead's shitty pet project"
  "an entirely commented out file"
  "a constructor for RandomThing"
  "circular imports"
  "a pull request with a winking smiley ;)"
  "the syntactic sugar coma"
  "former employees who still have admin access to live production servers"
  "the ib_logfiles"
  "the mysql client"
  "Paul Graham"
  "the much neglected IPv5"
  "cron jobs that edit cron jobs"
  "snail scale"
  "testing positive for mongonucleosis"
  "PEBKAC"
  "ReiserFS"
  "/dev/null"
  "Little Bobby Tables"
  "solar flares"
  "global warming"
  "short stroking"
  "reticulating splines"
  "RAID 3 SSD cluster"
  "re-implementing TCP over TCP"
  "mixed endianness"
  "OAuth"
  "traceroute"
  "rockstar"
  "packet loss"
  "smokeping"
  "losing the root password"
  "an engineer insisting \"it works on my machine!\""
  "malloc"
  "buffer overflow"
  "100 contractors wailing \"StackOverflow is OFFLINE?!\""
  "server logs"
  "penetration test"
  "deploying on a Friday afternoon"
  "Quipu"
  "too many authorization failures"
  "two single quotes"
  "kremvax"
  "the unix epoch"
  "0-day exploits"
  "tribal knowledge"
  "puppet"
  "RHEL4"
  "DevOps Reactions"
  "syntax errors"
  "killall -9"
  "pre caffeine typos"
  "banana pi"
  "RAID 0"
  "PIP"
  "PyPi"
  "synergy"
  "geometric distances"
  "out of bounds exceptions"
  "hunter2"
  "GCHQ"
  "NSA FOIA requests"
  "kanban"
  "Halt and Catch Fire"
  "Ansible"
  "template out"
  "bzero"
  "sendmail"
  "bare metal"
  "Slackware"
  "Bazaar"
  "runit"
  "a home-grown monitoring solution"
  "Virident"
  "ifconfig lo down"
  "Arch linux in production"
  "AUR"
  "Btrfs on a 2.6 kernel in production"
  "actually reading the manual"
  "telnetd on the payment tier"
  "the Hungary Games"
  "the GIL"
  "Solaris"
  "SmartOS"
  "Joyent"
  "Big-endian x86"
  "Uncyclopedia.org"
  "a flux capacitor"
  "a toaster on wheels"
  "the previous developer"
  "Debian experimental in production"
  "a server running an OS that hasn't been updated in 10 years"
  "HAL"
  "testing in production"
  "the Gang of Four becoming a real gang"
  "shoving the code down the compilers throat with catch statements"
  "legacy code that you're terrified of deleting"
  "that one goddamn line"
  "HTML5 vs Flash"
  "sudo: make me a sandwich"
  "Java's syntax"
  "the Travelling Salesman Problem"
  "Subjective C"
  "a neckbeard lamenting \"Ubuntu? I have to learn Ubuntu?\""
  "Dell custumer support"
  "the Genius Bar"
  "that goddamn paperclip"
  "laziness, impatience, and hubris"
  "a deleted StackOverflow post"
  "all our code becoming self-documenting because I declared it so"
  "VBScript, the future of software"
  "the waterfall model"
  "NaN"
  "undefined"
  "an empty int"
  "continous testing"
  "service virtualization"
  "test automation"
  "writing a Perl script to deploy Puppet Enterprise"
  "the OOM Killer"
  "$lastjob"
  "$i++"
  "tabs not spaces"
  "spaces not tabs"
  "spaces and tabs in the same file"
  "iptables"
  "Fedora Core 9"
  "\LaTeX{}"
  "NumPy"
  "an unmaintained man-page"
  "an old Gentoo installation"
  "null-pointer"
  "Delphi code from the 1990's"
  "turning it off and on again"
  "a PHP script comprised of shell_exec()'s"
  "a PHP script comprised of exec($_REQUEST['cmd'])"
  "Computer Science III"
  "multiple measurement systems"
  "date formats other than yyyy-mm-dd"
  "12 hour clocks"
  "clocks in a timezone other than UTC"
  "machines not running NTP"
  "using Fahrenheit instead of Celsius"
  "Classic Vi"
  "Mesos"
  "diva designer"
  "sudo chmod -R 777 /"
  "concurrent Javascript"
  "javascript programmers singing \"NaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaNNaN Batman!\""
  "Netscape Navigator"
  "Mosaic"
  "Adobe"
  "Microsoft"
  "Apple"
  "Samsung"
  "a new ultrabook"
  "binaries"
  "scope creep"
  "GitHub"
  "a Monad"
  "Silk Road"
  "--enable-h8"
  "--omg-optimized"
  "--funroll-loops"
  "--disable-instructions"
  "an old Solaris developer"
  "Dan Kaminsky"
  "being marked CLOSED WONTFIX"
  "a datacenter migration"
  "loading the servers in the back of a shady Canadian's truck"
  "the business acumen of the Mormon Church"
  "high latency"
  "the training budget"
  "SUID root"
  "regex golf"
  "a Monoid"
  "Slashdot"
  "quantum encryption"
  "JIRA Jr"
  "rm -rf Russian roulette"
  "errors which disappear in debug builds"
  "javascript webservers"
  "sysadmins sneaking Minecraft on the production server"
  "reporting bugs on IRC"
  "Emacs keyboard shortcuts"
  "DevOps podcasts"
  "Hamachi for VPN"
  "debugging Genetically Programmed code"
  "exchanging childhood memories for 160GiB of storage"
  "Saint IGNUcius"
  "--force"
  "gem native extensions"
  "anti-affinity"
  "multi factor authentication"
  "Python is the new Basic"
  "YAML"
  "cloud-agnostic"
  "Borland StarTeam"
  "a Python implementation that's basically just a whole bunch of C preprocessor macros"
  "the empty string language {ε} = Ø"
  "idempotence"
  "Chef-client running on OS/2 Warp"
  "@SwiftOnSecurity"
  "Adam Jacob's guitar"
  "PowerShell"
  "clock skew"
  "a good scotch collection at your desk"
  "a 1:1 that goes straight to the bar"
  "a 16 hour incident bridge"
  "something said by a NetEng that you didn't understand"
  "an obscure stack trace"
  "an app with no logging"
  "steering the Titanic with a popsicle stick"
  "a peer that doesn't believe in peer review"
  "Angular js"
  "a former MENSA member"
  "more bloat than GNU code"
  "Emacs pinky problems"
  "arguing over Java or C#"
  "best practices"
  "programming drunk"
  "custom Nagios scripts"
  "ITIL"
  "branded hoodies"
  "angel investors"
  "series B funding"
  "a noose made out of cat 5 cable"
  "a kernel hacker's beard"
  "the reaping of child processes"
  "nginx"
  "the outsourced IT department"
  "a NSFW MOTD file"
  "ASCII art"
  "bugzilla"
  "boto"
  "malicious code"
  "the return of the Y2K bug"
  "a highly sophisticated regular expression"
  "a mint-in-box AOL trial CD"
  "log aggregation"
  "the OWASP Top 10"
  "water-scrum-fall"
  "yet another attempt at re-writing Nagios"
  "infinite loops"
  "bareword variables"
  "rubocop"
  "a project of Stuxnet-level complexity"
  "Postgis"
  "Terraform"
  "AWK"
  "Greybeards"
  "Database antipatterns"
  "Cat5 'o 9 tails"
  "USB Type-C"
  "just plain text"
  "HTTP 418: I'm a teapot"
  "haveToMakeMyOwnArrayIsEmptyMethodBecauseCrappyJavaDoesNotHaveIt()"
  "a client with no servers"
  "rereading code of last night"
  "debugging 500 lines of code per method on average"
  "localhost"
  "the engineering deptartment responding \"can't reproduce; marking invalid and closing\""
  "unit testing randomization"
  "dropping tables on a Friday"
  "literally driving development"
  "while(true)"
  "using a switch for a boolean"
  "ENUM('Y','N');"
  "Mac OSX"
  "replacing all dev machines with Raspberry Pis"
  "redirecting www to dev"
  "the Cloud"
  "1337"
  "minorities in tech"
  "another Wordpress vulnerability"
  "a Raspberry Pi botnet"
  "DDoSing 127.0.0.1"
  "a low orbit ion cannon"
  "script kiddies"
  "hack forums"
  "/r/talesfromtechsupport"
  "@sadserver"
  "downtime"
  "Unixbeards"
  "excessivelyLongVariableNames"
  "a parent killing its children"
  "commenting every line of code"
  "DEFCON"
  "Richard Stallman"
  "emojis as identifiers"
  "trolling the sysadmins"
  "running Java 6"
  "UNDO UNDO UNDO"
  "the Hypertext Coffee Pot Control Protocol"
  "SONET to Sonnet Translation"
  "IP Over Avian Carriers with QoS"
  "SCCS"
  "the Infinite Monkey Protocol Suite"
  "a National Security Letter"
  "Hyper Text Coffee Pot Control Protocol for Tea Efflux Appliances (HTCPCP-TEA)"
  "NSA (No Secrecy Afforded) Certificate Extension"
  "scenic routing for IPv6"
  "Really Explicit Congestion Notification (RECN)"
  "Internet Explorer"
  "the Tor Network"
  "/dev/random"
  "Windows for Workgroups"
  "M-x dwim"
  "the ===== operator"
  "kibo"
  "comments written in Elvish"
  "comments written in Klingon"
  "comments written in Na'vi"
  "a blue box"
  "APL"
  "Snobol"
  "Bogosort"
  "the Jargon File"
  "AI-complete"
  "BCPL"
  "the ?= operator"
  "12 hamsters"
  "Selenium"
  "a server with no client"
  "trusting user input"
  "Guru Meditation"
  "unexpected T_PAAMAYIM_NEKUDOTAYIM"
  "402: Payment required"
  "treating warnings as errors"
  "turning up to work still drunk from yesterday"
  "private members"
  "EgoDB"
  "LISP"
  "git push --force"
  "a pi stack"
  "PBKAC"
  "Reddit"
  "a poorly abbreviated function name"
  "#nosemver"
  "the .sucks Domain"
  "the <blink> tag"
  "the <marquee> tag"
  "CTRL - C! CTRL - C! CTRL - C!"
  "Greg Case"
  "updating build.gradle"
  "the setting GIT_HISTORY_ALL_FUCKED_UP_IN_HERE = TURBO"
  "Cowboy Neal"
  "an insensitive clod"
  "one weird old trick"
  "copy pasta errors"
]
